### ISSUE TITLE
Roadmap v1

### ISSUE THREAD

**Issue by nathanschwarz** [Maagan-Michael/net-n#17]
Backend : 
app configuration :
- [ ] validate the app configuration with a proper `pydantic` model (this way the configuration can be precisely described in the documentation
- [ ] replace all bracket notations for the app configuration access with the class key (defined in the pydantic model).

job queue : 
- [ ] create a proper job queue class
- [ ] replace calls in the server lifecyle calls (start, shutdown)

IMC adapter:
- [ ] update all unreachable connections isUp flag

SwitchOutput in the API (pydantic) : 
- [ ] modify the ConnectionOutput and the SwitchOutput to include the unreachable boolean

Customer assignation (in "/upsert" and "/assign"):
- [ ] remove customer from previous connections and close the respective ports when assigned to an other connection (if `connection.autoUpdate == True`)

Customer deletion : 
- [ ] toggle off associated connections (if `connection.autoUpdate == True`)

Switch mutation : 
- [ ] if `restrictedPorts` has changed, find and update the `connection.autoUpdate = False` accordingly

Switch deletion : 
- [ ] close all connections to the switch(es)
- [ ] remove all associated connections

Frontend :
- [ ] add an indicator when a switched is marked as unreachable
- [ ] modify the switchOutput related types to include unreachable boolean

**Comment by yarons** [comment]
Regarding the HTML documentation? Can you add an explanation on how to do it and I'll try to see if there are any alternatives?

**Comment by nathanschwarz** [comment]
> Regarding the HTML documentation? Can you add an explanation on how to do it and I'll try to see if there are any alternatives?

The HTML documentation generated for the sync module was generated with `pdoc3`.
It's simple as :
`
pip install pdoc3
pdoc3 path_to_module
`
Unfortunately pdoc3 doesn't generate documentation for pydantic models and descriptions.

**Comment by yarons** [comment]
Apparently it requires a different module: https://docs.pydantic.dev/latest/concepts/models/

**Comment by yarons** [comment]
I'm not sure but maybe this will cover:
https://www.reddit.com/r/Python/comments/fqjxpp/i_created_an_autodoc_plugin_for_mkdocs/
